[package]
name = "log_reader"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
encoding_rs = "0.8.35"
iced = { version = "0.14.0", features = ["advanced", "tokio", "sipper"] }
sipper = "0.1.0"
tokio = { version = "1.48.0", featurea = ["full"] }
